[build]
  cmd = "go build -o ./tmp/main main.go"
  bin = "tmp/main"
  log = "build-errors.log"

[watch]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]

[serve]
  command = "./tmp/main"
  log = "serve.log"
